spio/ecommerce/web/src/main/java/pl/spio/menu/menuBean.java
package pl.spio.menu;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;

@ManagedBean
@ApplicationScoped
public class menuBean {
	public String userManagement() {
		return "/management/users.xhtml";
	}

	public String productManagement() {
		return "/management/products.xhtml";
	}
}

spio/ecommerce/web/src/main/java/pl/spio/session/SessionBean.java
package pl.spio.session;

import java.io.Serializable;
import java.security.Principal;
import java.util.ResourceBundle;

import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;

import pl.spio.ecommerce.account.IUserControllerBean;
import pl.spio.ecommerce.account.User;

@ManagedBean
@SessionScoped
public class SessionBean implements Serializable {
	@EJB
	private IUserControllerBean userController;
	private String username;
	private String password;
	private User user;

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public User getUser() {
		if (user == null) {
			Principal principal = FacesContext.getCurrentInstance()
					.getExternalContext().getUserPrincipal();
			if (principal != null) {
				user = userController.findUser(principal.getName());
			}
		}
		return user;
	}

	public boolean isUserLoggedIn() {
		return getUser() != null;
	}

	public String login() {
		FacesContext context = FacesContext.getCurrentInstance();
		HttpServletRequest request = (HttpServletRequest) context
				.getExternalContext().getRequest();
		try {
			request.login(username, password);
			getUser();
		} catch (ServletException e) {
			FacesMessage message = new FacesMessage(getText("unknown.login"));
			message.setSeverity(FacesMessage.SEVERITY_ERROR);
			context.addMessage("loginForm:username", message);
			return "";
		}
		return "start/index.xhtml?faces-redirect=true";
	}

	protected String getText(String key) {
		String text = null;
		try {
			ResourceBundle bundle = ResourceBundle.getBundle(
					"pl.spio.i18n.Text", FacesContext.getCurrentInstance()
							.getViewRoot().getLocale());
			text = bundle.getString(key);
		} catch (Exception e) {
			text = "???" + key + "???";
		}
		return text;
	}

	public String logout() {
		FacesContext.getCurrentInstance().getExternalContext()
				.invalidateSession();
		user = null;
		return "logout";
	}
}

spio/ecommerce/web/src/main/java/pl/spio/user/UserBean.java
package pl.spio.user;

import javax.annotation.ManagedBean;
import javax.ejb.EJB;
import javax.faces.bean.ViewScoped;

import pl.spio.ecommerce.account.IUserControllerBean;
import pl.spio.ecommerce.account.User;

@ManagedBean
@ViewScoped
public class UserBean {
	
	@EJB
	private IUserControllerBean userControllerBean;
	private User user;
	private long userId;

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}
	
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public void initUser()
	{
		user = userControllerBean.findUserByID(userId);
	}
	
}

spio/ecommerce/web/src/main/java/pl/spio/user/UsersBean.java
package pl.spio.user;

import java.util.List;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import pl.spio.ecommerce.account.User;
import pl.spio.ecommerce.account.IUserControllerBean;

@ManagedBean
@ViewScoped
public class UsersBean {
	@EJB
	private IUserControllerBean userControllerBean;
	private long userIdToRemove;
	private long userIdToEdit;
	

	public List<User> getAllUsers() {
		return userControllerBean.getAllUsers();
	}
	
	public User getUser() {
		return userControllerBean.findUserByID(userIdToEdit);
	}

	public void removeUser() {
		userControllerBean.removeUser(userIdToRemove);
	}

	public long getUserIdToRemove() {
		return userIdToRemove;
	}

	public void setUserIdToRemove(long userIdToRemove) {
		this.userIdToRemove = userIdToRemove;
	}
	
	public void setUserIdToEdit(long userIdToEdit) {
		this.userIdToEdit = userIdToEdit;
	}
}

spio/ecommerce/web/src/main/webapp/login.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<f:view>
	<h:body>
		<ui:composition template="/templates/layout.xhtml">
			<ui:define name="content">
				<h:form id="loginForm">
					<h:panelGrid id="grid" columns="1">
						<h:panelGroup>
							<h:outputLabel value="#{msg['username']}" for="username" />
							<h:inputText id="username" value="#{sessionBean.username}"
								required="true" />
							<h:message for="username" />
						</h:panelGroup>
						<h:panelGroup>
							<h:outputLabel value="#{msg['password']}" for="password" />
							<h:inputSecret id="password" value="#{sessionBean.password}"
								required="true" />
							<h:message for="password" />
						</h:panelGroup>
						<h:panelGroup>
							<h:commandButton action="#{sessionBean.login}"
								value="#{msg['login']}" />
						</h:panelGroup>
					</h:panelGrid>
				</h:form>
			</ui:define>
		</ui:composition>
	</h:body>
</f:view>
</html>

spio/ecommerce/web/src/main/webapp/management/products.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<f:view>
	<h:body>
		<ui:composition template="/templates/layout.xhtml">
			<ui:define name="content">
				<h:outputText styleClass="note" value="PRODUKTY_" />
			</ui:define>
		</ui:composition>
	</h:body>
</f:view>
</html>

spio/ecommerce/web/src/main/webapp/management/user.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<f:view>
	<h:body>
		<f:metadata>
			<f:viewParam id="id" name="id" value="#{userBean.userId}" />
			<f:event type="preRenderView" listener="#{userBean.initUser}" />
		</f:metadata>
		<ui:composition template="/templates/layout.xhtml">

			<rich:dataTable id="userTable" iterationStatusVar="it" var="user"
				value="#{usersBean.user}" rows="15">
				<rich:column>
					<h:inputText id="username" value="#{userBean.user.username}" required="true" />
					<h:message for="username" />
				</rich:column>
				<rich:column>
					<h:inputText id="firstname" value="#{userBean.user.firstname}"
						required="true" />
					<h:message for="username" />
				</rich:column>
				<rich:column>
					<h:inputText id="lastName" value="#{userBean.user.lastName}" required="true" />
					<h:message for="lastName" />
				</rich:column>
				<rich:column>
					<h:inputText id="groupname" value="#{userBean.user.group.groupname}"
						required="true" />
					<h:message for="groupname" />
				</rich:column>
				<rich:column>
					<h:inputText id="active" value="#{userBean.user.active}" required="true" />
					<h:message for="active" />
				</rich:column>
				<rich:column>
					<h:link id="edit" outcome="/management/user.xhtml">
						<h:graphicImage value="/images/icons/edit.gif" />
						<f:param name="id" value="#{user.id}" />
					</h:link>
				</rich:column>
			</rich:dataTable>
			</ui:define>
		</ui:composition>
	</h:body>
</f:view>
</html>

spio/ecommerce/web/src/main/webapp/management/users.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<f:view>
	<h:body>
		<ui:composition template="/templates/layout.xhtml">
			<ui:define name="content">
				<h:form id="userList">
					<rich:dataTable id="userTable" iterationStatusVar="it" var="user"
						value="#{usersBean.allUsers}" rows="15">
						<rich:column>
							<f:facet name="header">
								<h:link id="add" outcome="/management/user.xhtml">
									<h:graphicImage value="/images/icons/new.gif" />
								</h:link>
							</f:facet>
#{it.index}
</rich:column>
						<rich:column>
							<f:facet name="header">#{msg['user.username']}</f:facet>
#{user.username}
</rich:column>
						<rich:column>
							<f:facet name="header">#{msg['user.firstname']}</f:facet>
#{user.firstName}
</rich:column>
						<rich:column>
							<f:facet name="header">#{msg['user.lastname']}</f:facet>
#{user.lastName}
</rich:column>
						<rich:column>
							<f:facet name="header">#{msg['group.groupname']}</f:facet>
#{user.group.groupname}
</rich:column>
						<rich:column>
							<f:facet name="header">#{msg['user.active']}</f:facet>
#{user.active}
</rich:column>
						<rich:column>
							<h:link id="edit" outcome="/management/user.xhtml">
								<h:graphicImage value="/images/icons/edit.gif" />
								<f:param name="id" value="#{user.id}" />
							</h:link>
							<a4j:commandLink render="@none"
								oncomplete="#{rich:component('confirmRemoval')}.show()">
								<h:graphicImage value="/images/icons/delete.gif" />
								<a4j:param value="#{user.id}"
									assignTo="#{usersBean.userIdToRemove}" />
							</a4j:commandLink>
						</rich:column>
					</rich:dataTable>
					<rich:popupPanel id="confirmRemoval" autosized="true">
#{msg['user.remove.areyousure']}
<a4j:commandButton value="#{msg['cancel']}"
							onclick="#{rich:component('confirmRemoval')}.hide(); return false;" />
						<a4j:commandButton value="#{msg['delete']}"
							onclick="remove(); return false;" />
					</rich:popupPanel>
					<a4j:jsFunction name="remove" action="#{usersBean.removeUser}"
						render="userTable"
						oncomplete="#{rich:component('confirmRemoval')}.hide();" />
				</h:form>
			</ui:define>
		</ui:composition>
	</h:body>
</f:view>
</html>

spio/ecommerce/web/src/main/webapp/start/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<f:view>
	<h:body>
		<ui:composition template="/templates/layout.xhtml">
			<ui:define name="content">
				<h:outputText styleClass="note" value="something" />
			</ui:define>
		</ui:composition>
	</h:body>
</f:view>
</html>

spio/ecommerce/web/src/main/webapp/templates/content.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<body>
	<ui:composition>
/ jakiś content /
</ui:composition>
</body>
</html>

spio/ecommerce/web/src/main/webapp/templates/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<body>
	<ui:composition>
		<h:panelGroup class="page-footer" layout="block">
			<h:outputText styleClass="copyright-note" value="Copyright" />
		</h:panelGroup>
	</ui:composition>
</body>
</html>

spio/ecommerce/web/src/main/webapp/templates/header.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:a4j="http://richfaces.org/a4j"
	xmlns:rich="http://richfaces.org/rich"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<body>
	<ui:composition>

			<h:panelGroup class="page-header" layout="block">
				<h:form rendered="#{sessionBean.isUserLoggedIn()}">
					<rich:toolbar>
						<rich:dropDownMenu>
							<f:facet name="label">
								<h:panelGroup>
									<h:outputText value="#{msg['management.management']}" />
								</h:panelGroup>
							</f:facet>
							<rich:menuItem label="#{msg['management.user.management']}"
								action="#{menuBean.userManagement()}" />
							<rich:menuItem label="#{msg['management.product.management']}"
								action="#{menuBean.productManagement()}" />
						</rich:dropDownMenu>
						<rich:toolbarGroup location="right">
							<h:commandLink action="#{sessionBean.logout()}"
								value="#{msg['logout']}" />
						</rich:toolbarGroup>
					</rich:toolbar>
				</h:form>
			</h:panelGroup>
			
			
	</ui:composition>
</body>
</html>


spio/ecommerce/web/src/main/webapp/templates/layout.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<h:outputStylesheet name="styles.css" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
</h:head>
<h:body>
	<div id="page">
		<div id="header">
			<ui:insert name="header">
				<ui:include src="/templates/header.xhtml" />
			</ui:insert>
		</div>
		<div id="content">
			<ui:insert name="content">
				<ui:include src="/templates/content.xhtml" />
			</ui:insert>
		</div>
		<div id="footer">
			<ui:insert name="footer">
				<ui:include src="/templates/footer.xhtml" />
			</ui:insert>
		</div>
	</div>
</h:body>
</html>